<a href="https://colab.research.google.com/github/AXYUT-9/5CS037/blob/main/worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [99]:
import  numpy as np

In [100]:
arr_0d = np.array(5)
arr_1d = np.array([1,2,3,4,5])
arr_2d = np.array([[1,2,3], [4,5,6]])
arr_3d = np.array([[[1,2], [3,4], [5,6]]])

for i, arr in enumerate([arr_0d, arr_1d,arr_2d,arr_3d]):
  print(f"{i}D Array:\n{arr}\nShape: {arr.shape}\n")

0D Array:
5
Shape: ()

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]
  [5 6]]]
Shape: (1, 3, 2)



In [101]:
my_array = np.array([[1,2,3], [4,5,6]])
reshaped_array = my_array.reshape(3,2)
print(f"Original array : {my_array}\nReshaped array: {reshaped_array}")

Original array : [[1 2 3]
 [4 5 6]]
Reshaped array: [[1 2]
 [3 4]
 [5 6]]


In [102]:
a = np.arange(1, 10)
print(a)

x = range(1, 10)
print(x)
print(list(x))

x = np.arange(10.4)
print(x)

p = np.arange(0.5, 10.4, 0.8)
print(p)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [103]:
one_array = np.ones((2,3))
zeros_array = np.zeros((3, 2))
empty_array = np.empty((2, 2))
identity_matrix = np.eye((3))

print(one_array, zeros_array, empty_array, identity_matrix, sep='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[4.9e-324 9.9e-324]
 [1.5e-323 2.5e-323]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [104]:
array_from_list = np.array([1, 2, 3])
print(array_from_list)

array_from_tuple = np.array((4, 5, 6))
print(array_from_tuple)

array_from_nested_list = np.array([[1, 2, 3], [4, 5, 6]])
print(array_from_nested_list)


[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [105]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

zeros, ones, empty = np.zeros(arr.shape), np.ones(arr.shape), np.empty(arr.shape) # Shape: (2,3)
print(arr, zeros, ones, empty, sep='\n')

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [106]:
arrmy = np.array([1, 2, 3])
a = arrmy * 2
print(a)

copied_array = np.copy(arrmy)
print(copied_array)

sliced = arrmy[1:2]
print(sliced)

b = np.array([1,2,3,4,5])
slicing = b[1:3]
print(slicing)

[2 4 6]
[1 2 3]
[2]
[2 3]


In [107]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

concate_axis1 = np.concatenate((arr1, arr2), axis= 1)
print(concate_axis1)

[[1 2 5 6]
 [3 4 7 8]]


In [108]:
arr1d = np.array([0, 1, 2, 3, 4, 5])
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr3d = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]], [[8, 9], [10, 11]]])

print("Basic: ", arr1d[1:4], arr2d[::2, 1::2])

Basic:  [1 2 3] [[1]
 [7]]


In [109]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
result_dot = np.dot(A, B)
print(result_dot)

[[ 58  64]
 [139 154]]


In [110]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

result_at = A @ B
print("Result with @ operator:\n", result_at)

result_matmul = np.matmul(A, B)
print("Result with np.matmul:\n", result_matmul)

Result with @ operator:
 [[ 58  64]
 [139 154]]
Result with np.matmul:
 [[ 58  64]
 [139 154]]


In [111]:
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])

print(f"Inverse: \n {np.linalg.inv(A)} ")
print(f"Determinant: \n {np.linalg.det(A)} ")
print("Frobenius Norm:", np.linalg.norm(A, 'fro'))
print("2-Norm (Euclidean):", np.linalg.norm(A))
print("Solution x:", np.linalg.solve(A, B))

Inverse: 
 [[-2.   1. ]
 [ 1.5 -0.5]] 
Determinant: 
 -2.0000000000000004 
Frobenius Norm: 5.477225575051661
2-Norm (Euclidean): 5.477225575051661
Solution x: [-4.   4.5]


In [112]:
#Task 1
empty_array = np.empty((2,2))
print(empty_array)

[[1. 2.]
 [3. 4.]]


In [113]:
#Task 1 Q2
ones_array = np.ones((4,2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [114]:
#Q3
arr = np.full((2,3), 1, dtype= int)
print(arr)

[[1 1 1]
 [1 1 1]]


In [115]:
#Q4
zeros_arr = np.zeros((2,2))
print(zeros_arr)

[[0. 0.]
 [0. 0.]]


In [116]:
#Q5
ones_arr = np.ones((2,2))
print(ones_arr)

[[1. 1.]
 [1. 1.]]


In [117]:
#Q6
new_list = [1,2,3,4]
arr = np.array(new_list)
print(arr)

[1 2 3 4]


In [118]:
#task 2 Q1
arrnew = np.arange(10,49)
print(arrnew)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [119]:
#Q2
arr = np.arange(0,9)
reshaped_array = arr.reshape((3,3))
print(reshaped_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [120]:
#Q3
arr = np.random.random(size = 30)
meanarr = arr.mean()
print(meanarr)

0.498184389010868


In [121]:
#Q4
arr = np.random.random((10, 10))
max_Inarr = arr.max()
min_Inarr = arr.min()
print(max_Inarr)
print(min_Inarr)

0.9904054448996141
0.005309346328766895


In [122]:
#Q5
zero_arr = np.zeros(10)
zero_arr[4] = 1

print(zero_arr)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [123]:
#Q6
arr = [1,2,0,0,4,0]
reverse_arr = arr[::-1]
print(reverse_arr)

[0, 4, 0, 0, 2, 1]


In [124]:
#Q7
arrI = np.array([[1,0,1],[1,0,1]])
print(arrI)

[[1 0 1]
 [1 0 1]]


In [125]:
#Q8
arr = np.zeros((8,8), dtype = int)
arr[::2, 1::2] = 1
arr[1::2, ::2] = 1

print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [126]:
# TASK 3 Q1
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

#ADD
add_arr = x + y
print(f"Add array : \n {add_arr}")

#SUBTRACT
sub_arr = x - y
print(f"Subtract array : \n {sub_arr}")


#MULTIPLY
mulX_arr = x * 2
mulY_arr = y * 3
print(f"Multiply X array : \n {mulX_arr}")
print(f"Multiply Y array : \n {mulY_arr}")


#Square of each element of array
sqrX_arr = np.square(x)
sqrV_arr = np.square(v)
print(f"Sqaure of X: \n {sqrX_arr}")
print(f"Sqaure of V: \n {sqrV_arr}")


#dot product of v and w
dotPofvNw = np.dot(v,w)
print(f"Dot product of v and w: \n {dotPofvNw}")

#dot product of x and v
dotPofxNv = np.dot(x,v)
print(f"Dot product of v and w: \n {dotPofxNv}")


#dot product of x and y
dotPofxNy = np.dot(x,y)
print(f"Dot product of v and w: \n {dotPofxNy}")

#Concatenate x and y in row and Concatenate v and w in column
conarr0 = np.concatenate((x,y), axis = 0)
conarr1 = np.vstack((v,w)).T

print(f"Concatenate x and y \n {conarr0}")
print(f"Concatenate v and w \n {conarr1}")

Add array : 
 [[ 6  8]
 [10 13]]
Subtract array : 
 [[-4 -4]
 [-4 -3]]
Multiply X array : 
 [[ 2  4]
 [ 6 10]]
Multiply Y array : 
 [[15 18]
 [21 24]]
Sqaure of X: 
 [[ 1  4]
 [ 9 25]]
Sqaure of V: 
 [ 81 100]
Dot product of v and w: 
 219
Dot product of v and w: 
 [29 77]
Dot product of v and w: 
 [[19 22]
 [50 58]]
Concatenate x and y 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w 
 [[ 9 11]
 [10 12]]


In [127]:
#7
#Concatenate x n v
#arr = np.concatenate((x,v), axis = 0)
#print(f"Concatenate X and Y \n {arr}")

In [128]:
# Task 4 Q1
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# Prove A.A−1 = I

#Finding A.A-1
ainve = np.linalg.inv(A)
result1 = np.dot(A, ainve)
print(result1)
print(f"\n")


#Q1
#2
# To prove AB /= BA
# Finding AB

ab = np.dot(A,B)
print(ab)

ba = np.dot(B,A)
print(ba)

print(f"AB is not equal to BA")
print(f"\n")
#Q1
#3
# To Prove (AB)T = BTAT

#finding (AB)T

abTrans = ab.T
print(f"(AB)T  = \n {abTrans}")

#finding BTAT

btrans = B.T

atrans = A.T

btat = np.dot(btrans, atrans)
print(f"BTAT  = \n {btat} \n ")

print(f"(AB)T  = BTAT")

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
AB is not equal to BA


(AB)T  = 
 [[23 51]
 [13 29]]
BTAT  = 
 [[23 51]
 [13 29]] 
 
(AB)T  = BTAT


In [129]:
#Q2
A = np.array([[[2,-3,1], [1,-1,2], [3,1,-1]]])
B = np.array([-1,-3,9])
#Solving for: AX = B
ain = np.linalg.inv(A)
ainverb = np.dot(ain, B)
print(ainverb)

print(f"x = 2, y = 1, z = -2")


[[ 2.  1. -2.]]
x = 2, y = 1, z = -2


In [98]:

import time
import numpy as np

size = 1000000

# Python List

list1 = list(range(size))
list2 = list(range(size))

# Python LIST addition
start = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end = time.time()
print('Python list addition time:', end - start)


# NumPy

arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
res_np = arr1 + arr2
end = time.time()
print('Numpy addition time:', end - start)


# Multiplication


# Python LIST multiplication
start = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end = time.time()
print('Python list multiplication time:', end - start)

# NumPy multiplicatio
start = time.time()
res_np = arr1 * arr2
end = time.time()
print('Numpy multiplication time:', end - start)

# Dot Product


# Python LIST dot product
start = time.time()
res_list = sum(list1[i] * list2[i] for i in range(size))
end = time.time()
print('Python dot product time:', end - start)

# NumPy dot product
start = time.time()
res_np = np.dot(arr1, arr2)
end = time.time()
print('Numpy dot product time:', end - start)

# Matrix Multiplication


# large random matrices
A_big = np.random.random((1000, 1000))
B_big = np.random.random((1000, 1000))

A_list = A_big.tolist()
B_list = B_big.tolist()
start = time.time()
res = [
    [sum(a * b for a, b in zip(A_row, B_col)) for B_col in zip(*B_list)]
    for A_row in A_list
]
end = time.time()
print('Python matrix multiplication time:', end - start)

# NumPy matrix multiplication
start = time.time()
res_np = np.dot(A_big, B_big)
end = time.time()
print('Numpy matrix multiplication time:', end - start)

Python list addition time: 0.10760831832885742
Numpy addition time: 0.004703998565673828
Python list multiplication time: 0.13255548477172852
Numpy multiplication time: 0.004806041717529297
Python dot product time: 0.11006379127502441
Numpy dot product time: 0.0020351409912109375
Python matrix multiplication time: 188.48913049697876
Numpy matrix multiplication time: 0.0676870346069336
